db:
  image: mdillon/postgis:9.4
  container_name: gps_collector_db
  environment:
    POSTGRES_DB: gps_collector
    POSTGRES_PASSWD: gps_collector
    POSTGRES_USER: gps_collector
  ports:
    - "5430:5432"